services:
  apis:
    container_name: apis
    env_file:
      - ../.env
      - .env
    build:
      context: .
      dockerfile: build/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - /home/containers/portfolio:/home/containers/portfolio
    user: ${PUID}:${PGID}
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.apis.entryPoints=https
      - traefik.http.routers.apis.tls=true
      - traefik.http.routers.apis.middlewares=default@file

networks:
  proxy:
    external: true
